### ISSUE TITLE
Decide how many feed items to display

### ISSUE THREAD

**Issue by noplanman** [btcsumo/btcsumo#22]
We should decide on how many feed items to display.
At the moment the feeds get cached 1 month back.
But since some feeds don't post that often, maybe it makes sense to go 1 month back AND have a minimum of 30 posts. This way, there is some history that can be searchable for the future.

**Comment by tao67** [comment]
I will make a selection between the feeds and keep the active ones. We can try that, but I guess it will imply lower speed right ?

**Comment by noplanman** [comment]
What I meant was how many individual posts we keep in the cache, per feed.
At the moment I'm keeping posts from the past 30 days in the cache. Maybe we should change that to keep a minimum number instead of just going by number of days, since some feeds don't have that many new posts.
So I think it would make sense to say:
- Keep at least 30 posts
- If there are more than 30, keep posts from the last 30 days

What do you think?

**Comment by tao67** [comment]
I am worried about the speed. Maybe 20 posts would be enough ? Some blogs don't have more.

Yes I agree with this rule, if more, posts from the last 30 days is great.
